### PR TITLE
2.x – Use Eleventy to build documentation

### PR DESCRIPTION
**Pull request by gchtr**
This pull request is for the update to the new documentation generator using [Eleventy](https://www.11ty.dev/).

I’ve figured, that while [Hugo](https://gohugo.io/) is great for building static sites, it’s quite hard to work on new custom features. I was looking for other static site generators and first tried Gatsby, but then came back to [Eleventy](https://www.11ty.dev/) for its simplicity and ease of adding custom features.

So what’s better with this update?

- **Nunjucks** – We can use [Nunjucks](https://mozilla.github.io/nunjucks/) to build templates, which has the same syntax as Twig.
- **A better navigation** – I’ve built a custom script to build the navigation tree from the folder structure and the files in these folders. That way, we need to pass fewer meta data (front matter) to build the navigation.  
Also, the navigation is expanded all the time for a better overview over what’s in the different sections.
- **Updated styles** – I updated the colors a little and improved spacing between elements a bit. Not many people will notice the difference, I assume. I updated the code examples with Timber’s color scheme. We’ll see if that’s good enough or if we’d rather just take GitHub’s code style.
- **Sprinkles of JavaScript** I introduced [Turbolinks](https://github.com/turbolinks/turbolinks) as a progressive enhancement to a) load the pages even faster and b) make the navigation sidebar not scroll back to the top when clicking a link. And there’s some vanilla JavaScript for the mobile navigation.

## Other

- **Search should still work.** I will have to make a small pull request to the [**timber.json**](https://github.com/algolia/docsearch-configs/blob/master/configs/timber.json) file to fix some small things.
- **Redirects work differently.** To make redirects work with Eleventy, there’s now a central [**redirects.njk**](https://github.com/timber/timber/blob/2.x-docs-11ty/docs/v2/redirects.njk) file.
- Anchor links will be added to the headings themselves. This will make it easier to find a link to a section.
- Version switching works a little better than the one I envisioned with Hugo.

## How to test

It’s probably best to check out this branch and check the README. It should work to only run `npm run build`.

### CODE REVIEW

**Comment by jarednova** [comment]
@gchtr looks great! I was able to run things w/ only a few issues. We should take care of these before merging:

1. The one setup error I got was because of a hardcoded path in the `composer.lock`. I recommend we remove it from version control (I know this is counter to the [official recommendation](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control)) — but we don't track `composer.lock` in the main the main [timber/timber](https://github.com/timber/timber) repo and it makes life way easier.

2. Search works, however it takes you to the live site. When I use that path on the local test, it takes me to the 1.x version instead of the 2.x version

3. I get a build error in regards to a `pages` object ... 
```
] File changed: build/fonts/source-sans-pro-latin-700.woff2
[0] File changed: build/fonts/source-sans-pro-latin-700italic.woff
[0] File changed: build/fonts/source-sans-pro-latin-700italic.woff2
[0] File changed: build/fonts/source-sans-pro-latin-900.woff
[0] File changed: build/fonts/source-sans-pro-latin-900.woff2
[0] Problem writing Eleventy templates: (more in DEBUG output)
[0] > Cannot read property 'pages' of undefined
[0] 
[0] `TypeError` was thrown:
[0]     TypeError: Cannot read property 'pages' of undefined
[0]         at pageCollection (/Users/jared/VVV/www/docs/lib/pageCollection.js:19:24)
[0]         at Object.v2 (/Users/jared/VVV/www/docs/.eleventy.js:37:14)
[0]         at TemplateMap.getUserConfigCollection (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:451:47)
[0]         at TemplateMap.initDependencyMap (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:238:54)
[0]         at TemplateMap.cache (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:282:16)
[0]         at process._tickCallback (internal/process/next_tick.js:68:7)
[0] Using pathPrefix: /docs/
[0] Wrote 0 files in 0.03 seconds (v0.10.0)
[0] File changed: build/fonts/source-sans-pro-latin-900italic.woff
[0] File changed: build/fonts/source-sans-pro-latin-900italic.woff2
[1] <s> [webpack.Progress] 100% 
[1] 
[1]               Asset      Size   Chunks                   Chunk Names
[1]     /css/mobile.css  3.59 KiB  /js/app  [emitted]        /js/app
[1] /css/mobile.css.map  9.41 KiB  /js/app  [emitted] [dev]  /js/app
[1]     /css/styles.css  15.1 KiB  /js/app  [emitted]        /js/app
[1] /css/styles.css.map  39.4 KiB  /js/app  [emitted] [dev]  /js/app
[1]          /js/app.js  61.9 KiB  /js/app  [emitted]        /js/app
[1]      /js/app.js.map  72.5 KiB  /js/app  [emitted] [dev]  /js/app
[0] File changed: build/mix-manifest.json
[0] File changed: _data/mixManifest.json
[0] You saved while Eleventy was running, let’s run again.
[0] Problem writing Eleventy templates: (more in DEBUG output)
[0] > Cannot read property 'pages' of undefined
[0] 
[0] `TypeError` was thrown:
[0]     TypeError: Cannot read property 'pages' of undefined
[0]         at pageCollection (/Users/jared/VVV/www/docs/lib/pageCollection.js:19:24)
[0]         at Object.v2 (/Users/jared/VVV/www/docs/.eleventy.js:37:14)
[0]         at TemplateMap.getUserConfigCollection (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:451:47)
[0]         at TemplateMap.initDependencyMap (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:238:54)
[0]         at TemplateMap.cache (/Users/jared/VVV/www/docs/node_modules/@11ty/eleventy/src/TemplateMap.js:282:16)
[0]         at process._tickCallback (internal/process/next_tick.js:68:7)
[0] Using pathPrefix: /docs/
```

... I couldn't tell if that was actually affecting any output. It still built successfully and no other issues in use besides the search thing.

Let me know how this sounds, or if these are better handled in any other open PRs

**Comment by gchtr** [comment]
Thanks for checking it out!

> The one setup error I got was because of a hardcoded path in the `composer.lock`. I recommend we remove it from version control (I know this is counter to the [official recommendation](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control)) — but we don't track `composer.lock` in the main the main [timber/timber](https://github.com/timber/timber) repo and it makes life way easier.

The absolute path issue should be fixed now.

I’d rather have the **composer.lock** file in the repository. I think it’s a different use case, because whenever you run a build for the documentation, it should always do it with the same dependencies. Only the content should change. Timber is different there, because Timber is actually a dependency in itself.

Updating the dependencies should be a controlled task where you test afterwards that everything still works fine.

The best example is probably what happened in the current docs with the code blocks going rogue (https://github.com/timber/docs/commit/3c39e263c9319e9db6e01a8d891d5b2575d2f97b) because of a newer Hugo version.

> Search works, however it takes you to the live site. When I use that path on the local test, it takes me to the 1.x version instead of the 2.x version

I just asked the Algolia team how we could best handle different versions of Timber. We will have to update the [search config](https://github.com/algolia/docsearch-configs/blob/master/configs/timber.json), but probably only as soon as the new docs are live.

>  I get a build error in regards to a `pages` object ...

I forgot to mention it, but did you check out the [`2.x-docs-11ty`](https://github.com/timber/timber/tree/2.x-docs-11ty) branch in the Timber repository before running the build?

**Comment by jarednova** [comment]
The reasoning on `composer.lock` makes sense as does the Algolia config once it's launched. 

In regards to the build error, I checked and I'm running the `2.x-docs-11ty` branch in Timber. I don't observe any actual problems with the output on `localhost:8080` (I seem to be able to navigate around both the 1.x and 2.x versions w/o issue). The error only occurs with `npm run watch` (`npm run build` executes successfully). Long way of saying that I don't think it requires further investigation unless it's really driving you mad.

**Review by jarednova — APPROVED** [review]

**Comment by jarednova** [comment]
Any reason that this can't be merged and deployed prior to main Timber 2.x release? I actually like having the idea of having the info out ahead of the official release (esp. things like the upgrade guide). Perhaps the only change would be to default to the `1.x` pages where users land

**Comment by gchtr** [comment]
> In regards to the build error, I checked and I'm running the `2.x-docs-11ty` branch in Timber. I don't observe any actual problems with the output on `localhost:8080` (I seem to be able to navigate around both the 1.x and 2.x versions w/o issue). The error only occurs with `npm run watch` (`npm run build` executes successfully). Long way of saying that I don't think it requires further investigation unless it's really driving you mad.

Oh I see. I’ll fix that.

> Any reason that this can't be merged and deployed prior to main Timber 2.x release? I actually like having the idea of having the info out ahead of the official release (esp. things like the upgrade guide). Perhaps the only change would be to default to the `1.x` pages where users land

I was actually thinking about that too. I’ll add the changes so that we can access the documentation for the development version of 2.x. I’ll have to make sure to include a big notice so that everybody knows that this will be an upcoming version. And I’ll probably have to prevent search engines from indexing the development version.

> > Search works, however it takes you to the live site. When I use that path on the local test, it takes me to the 1.x version instead of the 2.x version
> 
> I just asked the Algolia team how we could best handle different versions of Timber. We will have to update the [search config](https://github.com/algolia/docsearch-configs/blob/master/configs/timber.json?rgh-link-date=2020-05-19T20%3A11%3A23Z), but probably only as soon as the new docs are live.

Apparently, we can use meta tags to customize the search for different versions: https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags

If we already have a live documentation for v2, we can work on getting search to work in parallel.

More updates coming!

**Comment by gchtr** [comment]
Okaaay, this should now be ready in combination with https://github.com/timber/timber/pull/2206.

The bug with `npm run watch` should be fixed.

I made v1 the default version and marked v2 as a DEV version. To make it absolutely clear, I added a big notice to all v2 documentation pages.

Bildschirmfoto 2020-06-03 um 20 50 52

I also added a `nofollow` meta tag for the version 2 pages, because we don’t want the `/docs/v2` path to be indexed by search engines just yet. V2 will become the default version as soon as it will be released. V1 will move to `/docs/v1`, which we’ll want search engines to index.

I realized that updating the documentation for v1 will still be a little problem, because we now use a different generator for the reference, that doesn’t work with PHP files from v1 just yet. We’ll probably have to fix some DocBlock bugs and add some `@api` tags to Timber v1 to make it work. But I can get to that when we need it.

We should merge in https://github.com/timber/timber/pull/2206 first and add the files generated by `npm run build`, and then we can merge this into `master`. As soon as we do, the new documentation will be live.

**Review by jarednova — APPROVED** [review]

**Comment by jarednova** [comment]
Great stuff! I was able to run now w/o any errors or issues. Very smart call on the `nofollow` — I can see how that could cause confusion for Google searchers.

The merge order stuff makes sense, but as I noted in [#2206](https://github.com/timber/timber/pull/2206/files#submit-review) I'll let you execute to make sure the details are followed and you can watch out for any snags.

Finally, 🎉  congrats 🎉  on this. You rebuilt the entire docs engine, integrated the 2.x knowledge and created a great UI to navigate between the versions. That's some 🎩 's off work!

**Pull request merged**
