### PR TITLE
Add feature to toggle between light mode and dark mode `wip`

### PR DESCRIPTION
**Pull request by heybran**
## Issue

As described in #78 

## Solution

Adding a theme toggle button on header to allow users to switch between light mode and dark mode. This is an draft PR submitting for a review as I didn't include the build files at this PR.

### CODE REVIEW

**Comment by Levdbas** [comment]
@heybran,

Let's move the discussion over here for your PR. I added a commit to give you some examples on how the css styling could also work. Please take a look and see if you think that would be a good thing to do on all places where the `html[data-theme="light"] & {` overrides are used.

I think it would make the whole css experience cleaner and the css easier to maintain as well.

Other than that, amazing job!

**Comment by heybran** [comment]
Sure thing. Will check it again once I'm free up.

**Comment by heybran** [comment]
@Levdbas 

I've finally scheduled time to finish up replacing the CSS overrides with custom properties, and you're absolutely right, it does make things more clean and easier to maintain. Please let me know if this is good or there's some areas that still need improvements. Thanks.

**Comment by Levdbas** [comment]
Amazing work @heybran !

Looks really good! I went though the pages and found only a few small things.

http://localhost:8080/docs/v2/reference/timber-pagesmenu/

- [x] **These links are hard to read in the light mode:**

image

-------------------


http://localhost:8080/docs/v2/reference/timber-post/

- [x] **The regular code snippets might need a bit more contrast:**

image

- [x] `h2 code` headings have changed

: http://localhost:8080/docs/v2/guides/twig-filters/ compared to https://timber.github.io/docs/v2/guides/twig-filters/
image

**Comment by heybran** [comment]
@Levdbas 

Thanks for the previous feedbacks. I've sent another batch of updates to improve the color contract on the prism code block, although I haven't got enough time to go through all pages and check everything. **I will find another time to QA my work and give it another test run on the color contract on the site.**

## Here's few updates of this commit:

### 1. Increase token contract ratio to AAA.
SCR-20240912-kgdr

### 2. Increase punctuation contract ratio to AAA.
SCR-20240912-khqe

### 3. Increase token string contract ratio to AAA.
SCR-20240912-kjkn

### 4. Increase php tag contract ratio to AAA.
SCR-20240912-kkxn

### 5. Increase constant/boolean contract ratio to AAA.
SCR-20240912-kntm

### 6. Fix this layout issue.
SCR-20240912-ksyb

**Review by Levdbas — APPROVED** [review]
Amazing work @heybran!

**Comment by Levdbas** [comment]
And your work is now live for everyone to enjoy! https://timber.github.io/docs/v2/

**Pull request merged**
